module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🚀 1. Getting Started',
      items: [
        'intro',
        'getting-started',
        'folder-structure',
      ],
    },
    {
      type: 'category',
      label: '⚙️ 2. Engineering Standard',
      items: [
        'coding-style',
        'state-management',
        'api-guide',
        'scss-guide',
        'hooks-guide',
        'performance',
        'security',
      ],
    },
    {
      type: 'category',
      label: '📂 3. Architecture & Decisions',
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
        'testing',
        'deployment',
        'ci-cd',
        'changelog-guide',
      ],
    },
    {
      type: 'category',
      label: '🤝 4. Team Synergy',
      items: [
        'a11y',
        {
          type: 'category',
          label: 'App/WebView Bridge',
          items: ['egov-bridge/README'],
        },
        'components',
        'html-tags-guide',
      ],
    },
    {
      type: 'category',
      label: '📚 Appendix',
      items: [
        'troubleshooting',
        'common-warnings',
        'references',
      ],
    },
  ],
};
