module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🚀 1. 시작하기',
      items: [
        { type: 'doc', id: 'intro', label: '소개' },
        { type: 'doc', id: 'getting-started', label: '환경 설정' },
        { type: 'doc', id: 'folder-structure', label: '폴더 구조' },
      ],
    },
    {
      type: 'category',
      label: '⚙️ 2. 엔지니어링 표준',
      items: [
        { type: 'doc', id: 'coding-style', label: '코딩 스타일' },
        { type: 'doc', id: 'state-management', label: '상태 관리' },
        { type: 'doc', id: 'api-guide', label: 'API 가이드' },
        { type: 'doc', id: 'scss-guide', label: 'SCSS 가이드' },
        { type: 'doc', id: 'hooks-guide', label: 'Hooks 가이드' },
        { type: 'doc', id: 'performance', label: '성능 최적화' },
        { type: 'doc', id: 'security', label: '보안 가이드' },
      ],
    },
    {
      type: 'category',
      label: '📂 3. 아키텍처 및 의사결정',
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
        { type: 'doc', id: 'testing', label: '테스트' },
        { type: 'doc', id: 'deployment', label: '배포' },
        { type: 'doc', id: 'ci-cd', label: 'CI/CD' },
        { type: 'doc', id: 'changelog-guide', label: '변경 이력 관리' },
      ],
    },
    {
      type: 'category',
      label: '🤝 4. 팀 시너지',
      items: [
        { type: 'doc', id: 'a11y', label: '웹 접근성' },
        {
          type: 'category',
          label: '앱/웹뷰 브릿지',
          items: [{ type: 'doc', id: 'egov-bridge/README', label: '브릿지 가이드' }],
        },
        { type: 'doc', id: 'components', label: '공통 컴포넌트' },
        { type: 'doc', id: 'html-tags-guide', label: 'HTML 태그 가이드' },
      ],
    },
    {
      type: 'category',
      label: '📚 부록',
      items: [
        { type: 'doc', id: 'troubleshooting', label: '트러블슈팅' },
        { type: 'doc', id: 'common-warnings', label: '자주 발생하는 경고' },
        { type: 'doc', id: 'references', label: '참고 자료' },
      ],
    },
  ],
};
